# Discussion

## Methods

@colombo_estimation_2008 also performed PROSPECT inversion to estimate leaf water and dry matter contents.
They were able to estimate EWT with no prior information, but that simultaneous estimation of EWT and LDMC was more challenging.

Leaf water content tends to confound the extraction of other leaf constituents, particularly dry matter content [@kokaly_spectroscopic_1999]. 
This may help explain the large uncertainties in our estimates of dry matter content.

The relationship between leaf dry matter content (for which we had no direct measurements in this study) and leaf mass per area is unclear.
Some studies have assumed that the two traits are comparable [e.g. @cheng_deriving_2014], but other studies that have explored the correlations explicitly found that is not necessarily the case (**REFS**).

## Ecology

Genetic basis behind leaf economic spectrum [@donovan_evolution_2011].

LMA trends in evergreen leaves; e.g. shade tolerance [@lusk_why_2008].

Importance of intraspecific variability in ecology, and how to study it [@violle_return_2012].

@asner_amazonian_2014 -- Very similar to this study. Lots of points of comparison. Look for ways to replicate analyses.

@asner_functional_2014 -- Also very similar. Look at his GLM approach.

In ponderosa pine-Gambel oak, mixed conifer, and subalpine forests (US Southwest, Arizona, near Grand Canyon), specific leaf area increased in mean (decreased LMA) and variance (increased for LMA too) [@laughlin_predictive_2012].
@laughlin_predictive_2012 also observed high variance in traits -- as much as 60% -- for a given MAT.

In grazed, semi-natural grasslands in Europe, plant life history (**which traits?**) associated with availabile phosphorus, while grazing intensity is related to C:N ratio. 
Specifically, SLA increased (LMA decreased) with disturbance intensity, while onset of flowering and C:N ratio decreased. 
Phosphorus was positively related to SLA (negatively to LMA) and onset of flowering, and negatively related to C:N ratio, seed mass, and polycarpic life history (?) [@kleyer_assessing_2012].

@laughlin_multi-trait_2010 has evidence of leaf economic relationships in ponderosa pine forest in northern Arizona; high SLA (low LMA) species also have high leaf and fine root N and low leaf dry matter content.

Among Australian eucalypt taxa, low SLA (high LMA) improves the response of short species to rainfall and sunlight; tall species increased with rainfall and sunlight over all SLA values, but low SLA (high LMA) species were particularly sensitive to rainfall [@pollock_role_2012].

@pierce_allocating_2013 treat find that LDMC is strongly negatively correlated with SLA (positively with LMA) and, more weakly, with leaf N, and strongly positively correlated with leaf C.

@roth_leaf_2016 -- Three different principal components of spectral variability.
PC1 correlates best with leaf structure and surface scattering.
PC2 correlates best with lignin, water, and LMA.
PC3 correlates with surface scattering and pigments.

Coexistence depends on competition being stronger within than between species [@clark_individuals_2010] (**More theory on this**).

The future is remote sensing of functional traits.
Remote sensing provides an approach to overcoming the inherent issues with space for time substitution by measuring ecosystem responses to climate change directly through time [@clark_climate_2011].


## Other notes

Although the _N_ parameter is supposed to represent the effective number of leaf mesophyll layers (or 1 more than the number of leaf intracellular air spaces), its global modulation of reflectance may mean it is also influenced by spectrally invariant specular reflectance off the leaf surface.

The composition of the leaf surface, such as cutin and wax, may also be related to the leaf dry matter content absorption coefficient [@da_luz_attenuated_2006].

Early efforts to extent the PROSPECT model to additional compounds like lignin, cellulose, and protein [e.g. @jacquemoud_estimating_1996; @fourty_leaf_1996] have been largely abandoned by the community in favor of empirical approaches like PLSR, wavelets, etc.
However, we suggest that such efforts be revisited.

Moving from the leaf to the canopy scale is challenging.
Wavelengths of most importance for estimating traits (e.g. pigments, @yoder_predicting_1995) may be different at the leaf and canopy scales due to confounding influences of structural variables.
This is why it is important to use and enhance radiative transfer models.

However, remote retrievals using inversion of coupled leaf and canopy radiative transfer models are promising [@jacquemoud_inversion_1993; @jacquemoud_extraction_1995].


# References
